import React from "react";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

interface rootProps {
  children: React.ReactElement
  canva: React.ReactElement
}

export default function RootLayout({ children,canva }: Readonly<rootProps>) {
  return (
    <html lang="ptBR">
      <body className={inter.className}>
        {children}
        {canva}
        </body>
    </html>
  );
}
